@startuml
set namespaceSeparator ::
abstract class "book_crossing_app::AuthorRepository" {
  +Future<List<Author>> getAllAuthors()
  +Future<Author> createAuthor()
}

abstract class "book_crossing_app::AuthRepository" {
  +Future<User> signIn()
  +Future<User> signUp()
}

abstract class "book_crossing_app::PointRepository" {
  +Future<List<PickUpPoint>> getAllPoints()
  +Future<List<PickUpPoint>> getUserPoints(User user)
  +Future<void> deletePoint(int id)
  +Future<PickUpPoint> createPoint()
  +Future<PickUpPoint> updatePoint()
}

abstract class "book_crossing_app::BookRepository" {
  +Future<List<Book>> getAllBooks()
  +Future<Book> createBook()
}

abstract class "book_crossing_app::StatusRepository" {
  +Future<List<Status>> getAllStatuses()
}

abstract class "book_crossing_app::TransferRepository" {
  +Future<List<Transfer>> getAllTransfers()
  +Future<Transfer> getTransfers()
  +Future<List<Transfer>> getUserTransfers()
  +Future<Transfer> makeRequest()
  +Future<Transfer> makeTransfer()
  +Future<List<Transfer>> getBookTransfers()
  +Future<Transfer> createTransfer()
}
abstract class "book_crossing_app::GenreRepository" {
  +Future<List<Genre>> getAllGenres()
}

abstract class "book_crossing_app::LikeRepository" {
  +Future<Review> likeReview()
}

abstract class "book_crossing_app::PreferencesRepository" {
  +Future<String?> getUser()
  +Future<void> saveProfile()
  +Future<void> saveTheme()
  +Future<ThemeMode> loadThemeMode()
  +Future<void> removeSavedProfile()
}

abstract class "book_crossing_app::ProfileRepository" {
  +Future<User> getProfile()
  +Future<User> updateProfile()
  +Future<User> removeImage()
}

abstract class "book_crossing_app::ReviewRepository" {
  +Future<List<Review>> getUsersReview()
  +Future<List<Review>> getAllReviews()
  +Future<Review> addReview()
  +Future<Review> archiveReview()
  +Future<Review> unzipReview()
  +Future<void> deleteReview()
}

class "book_crossing_app::main.dart::MyApp" {
  +Widget build()
}

@enduml
